version: '3'

services:
  mysqldb:
    image: mysql:8.2.0
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: asi
      MYSQL_USER: msqladmin
      MYSQL_PASSWORD: msqladmin
      MYSQL_ROOT_PASSWORD: msqladmin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio: 
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  db-data:
  minio-data: